name: Lint
on: [pull_request, push]
permissions:
  checks: write
  contents: write
jobs:
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Check OS Version
        run: uname -a
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check versions
        run: python --version && pip --version
      - name: Check out main repository
        uses: actions/checkout@v4
      - name: Install Black
        run: pip install black

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          auto_fix: true
          black: true
          black_auto_fix: true